// Central field registry — source of truth for all field metadata.
// Add new fields HERE before touching toolSchema.js, fusionExport.js, or proShopExport.js.
//
// Field entry shape:
//   label          — display label (matches FIELD_LABELS in toolSchema.js)
//   type           — 'number' | 'string' | 'boolean' | 'array'
//   unit           — 'length' | 'angle' | 'speed' | 'feed' | 'rpm' | null
//   canonicalUnit  — for length fields only: how the value is STORED internally.
//                    'native'  = the tool's own unit (mm for a metric tool) —
//                                read raw from / written raw to Fusion.
//                    'inches'  = always inches regardless of the tool's unit
//                                (OOH / min_ooh) — convert at any boundary with a
//                                native length via inchesToNative(). See the Units
//                                section in CLAUDE.md and FUSION_SCHEMA.md §1e.
//                    Absent on non-length fields.
//   fusionPath     — dot-path into Fusion JSON (null = not written to Fusion)
//   proShopColumn  — PS CSV column header (null = not directly exported to ProShop)
//   metadataOnly   — true = never written to Fusion JSON (lives in tool_metadata.json only)
//   appliesToTypes — 'all' | string[] of tool types this field applies to
//   required       — true = always required for a valid tool (from validateTool())
//   precision      — display decimal places for numeric fields, null otherwise

// All 26 tool types — mirrors TT from tool-extractor.tsx (duplicated to avoid circular dep)
const ALL_TYPES = [
  'flat end mill', 'ball end mill', 'bull nose end mill', 'tapered mill', 'radius mill',
  'form mill', 'lollipop mill', 'slot/key cutter', 'dovetail', 'thread mill', 'face mill',
  'chamfer mill', 'circle segment barrel', 'circle segment lens', 'circle segment oval',
  'circle segment taper', 'drill', 'center drill', 'spot drill', 'reamer', 'counter bore',
  'counter sink', 'tap form', 'tap cut', 'boring head', 'turning general',
];

// Reusable applicability subsets (derived from tool-extractor.tsx FIELD_VISIBILITY)
const NO_TURNING      = ALL_TYPES.filter(t => t !== 'turning general');
const NO_BORING_TURN  = ALL_TYPES.filter(t => t !== 'boring head' && t !== 'turning general');
const NO_BORING       = ALL_TYPES.filter(t => t !== 'boring head');

export const FIELD_REGISTRY = {

  // ── Identity & System ─────────────────────────────────────────────────────

  tool_type: {
    label: 'Tool Type',
    type: 'string',
    unit: null,
    fusionPath: 'type',
    proShopColumn: null,
    metadataOnly: false,
    appliesToTypes: 'all',
    required: true,
    precision: null,
  },

  description: {
    label: 'Description',
    type: 'string',
    unit: null,
    fusionPath: 'description',
    proShopColumn: null,          // PS 'description' column is auto-generated by buildDesc()
    metadataOnly: false,
    appliesToTypes: 'all',
    required: true,
    precision: null,
  },

  unit: {
    label: 'Unit',
    type: 'string',
    unit: null,
    fusionPath: 'unit',
    proShopColumn: null,
    metadataOnly: false,
    appliesToTypes: 'all',
    required: false,
    precision: null,
  },

  // ── Identity (procurement) ────────────────────────────────────────────────

  vendor: {
    label: 'Manufacturer',
    type: 'string',
    unit: null,
    fusionPath: null,             // NEVER written to Fusion JSON (see CLAUDE.md)
    proShopColumn: 'approvedBrand',
    metadataOnly: true,
    appliesToTypes: 'all',
    required: false,
    precision: null,
  },

  product_id: {
    label: 'Mfr Part # (EDP)',
    type: 'string',
    unit: null,
    fusionPath: null,             // metadata only; proshot_id goes to Fusion product-id
    proShopColumn: 'EDP#',
    metadataOnly: true,
    appliesToTypes: 'all',
    required: false,
    precision: null,
  },

  proshot_id: {
    label: 'ProShop ID',
    type: 'string',
    unit: null,
    fusionPath: 'product-id',     // Fusion's product-id field = our ProShop ID
    proShopColumn: null,
    metadataOnly: false,
    appliesToTypes: 'all',
    required: false,
    precision: null,
  },

  distributor: {
    label: 'Distributor',
    type: 'string',
    unit: null,
    fusionPath: null,
    proShopColumn: 'vendor',      // confusingly, PS names the distributor column "vendor"
    metadataOnly: true,
    appliesToTypes: 'all',
    required: false,
    precision: null,
  },

  distributor_stock_num: {
    label: 'Distributor Stock #',
    type: 'string',
    unit: null,
    fusionPath: null,
    proShopColumn: null,
    metadataOnly: true,
    appliesToTypes: 'all',
    required: false,
    precision: null,
  },

  cost: {
    label: 'Cost ($)',
    type: 'string',
    unit: null,
    fusionPath: null,
    proShopColumn: 'cost',
    metadataOnly: true,
    appliesToTypes: 'all',
    required: false,
    precision: 2,
  },

  product_link: {
    label: 'Product Link',
    type: 'string',
    unit: null,
    fusionPath: 'product-link',
    proShopColumn: null,
    metadataOnly: false,
    appliesToTypes: 'all',
    required: false,
    precision: null,
  },

  location: {
    label: 'Location (Cabinet)',
    type: 'string',
    unit: null,
    fusionPath: 'expressions.tool_vendor', // Fusion's "Vendor" UI field repurposed as cabinet location
    proShopColumn: null,
    metadataOnly: false,
    appliesToTypes: 'all',
    required: false,
    precision: null,
  },

  grouping: {
    label: 'ProShop Group',
    type: 'string',
    unit: null,
    fusionPath: null,
    proShopColumn: 'toolGroupLetter',
    metadataOnly: true,
    appliesToTypes: 'all',
    required: false,
    precision: null,
  },

  preset_name: {
    label: 'Preset Name',
    type: 'string',
    unit: null,
    fusionPath: null,
    proShopColumn: null,
    metadataOnly: true,
    appliesToTypes: 'all',
    required: false,
    precision: null,
  },

  tool_number: {
    label: 'Tool Number',
    type: 'string',
    unit: null,
    fusionPath: 'post-process.number',
    proShopColumn: null,
    metadataOnly: false,
    appliesToTypes: 'all',
    required: false,
    precision: null,
  },

  machine_tool_number: {
    label: 'Machine Tool #',
    type: 'number',
    unit: null,
    fusionPath: 'post-process.number', // metadata is source of truth; also mirrored to Fusion
    proShopColumn: null,
    metadataOnly: false,               // written to Fusion post-process, but metadata wins
    appliesToTypes: 'all',
    required: false,
    precision: 0,
  },

  // ── Geometry ──────────────────────────────────────────────────────────────

  diameter: {
    label: 'Diameter (in)',
    type: 'number',
    unit: 'length',
    canonicalUnit: 'native',
    fusionPath: 'geometry.DC',
    proShopColumn: 'cutDiameter',
    metadataOnly: false,
    appliesToTypes: 'all',
    required: true,
    precision: 4,
  },

  flute_length: {
    label: 'Flute Length (in)',
    type: 'number',
    unit: 'length',
    canonicalUnit: 'native',
    fusionPath: 'geometry.LCF',
    proShopColumn: 'lengthOfCut',
    metadataOnly: false,
    appliesToTypes: NO_BORING_TURN,
    required: false,
    precision: 4,
  },

  overall_length: {
    label: 'Overall Length (in)',
    type: 'number',
    unit: 'length',
    canonicalUnit: 'native',
    fusionPath: 'geometry.OAL',
    proShopColumn: 'overallLength',
    metadataOnly: false,
    appliesToTypes: 'all',
    required: false,
    precision: 4,
  },

  number_of_flutes: {
    label: '# Flutes',
    type: 'number',
    unit: null,
    fusionPath: 'geometry.NOF',
    proShopColumn: 'no. of flutes',
    metadataOnly: false,
    appliesToTypes: NO_BORING,
    required: false,
    precision: 0,
  },

  shank_diameter: {
    label: 'Shank Diameter (in)',
    type: 'number',
    unit: 'length',
    canonicalUnit: 'native',
    fusionPath: 'geometry.SFDM',
    proShopColumn: 'shankDiameter',
    metadataOnly: false,
    appliesToTypes: NO_TURNING,
    required: false,
    precision: 4,
  },

  corner_radius: {
    label: 'Corner Radius (in)',
    type: 'number',
    unit: 'length',
    canonicalUnit: 'native',
    fusionPath: 'geometry.RE',
    proShopColumn: 'cornerRadius',
    metadataOnly: false,
    appliesToTypes: [
      'bull nose end mill', 'tapered mill', 'radius mill',
      'dovetail', 'lollipop mill', 'circle segment lens',
    ],
    required: false,
    precision: 4,
  },

  shoulder_length: {
    label: 'Shoulder Length (in)',
    type: 'number',
    unit: 'length',
    canonicalUnit: 'native',
    fusionPath: 'geometry.shoulder-length',
    proShopColumn: null,
    metadataOnly: false,
    appliesToTypes: NO_TURNING,
    required: false,
    precision: 4,
  },

  tip_angle: {
    label: 'Tip Angle (°)',
    type: 'number',
    unit: 'angle',
    fusionPath: 'geometry.SIG',   // drill/spot/chamfer point (included) angle — Fusion-native
    proShopColumn: 'tipAngle',
    metadataOnly: false,
    appliesToTypes: [
      'chamfer mill', 'drill', 'center drill', 'spot drill', 'counter sink',
    ],
    required: false,
    precision: 4,
  },

  taper_angle: {
    label: 'Taper Angle (°)',
    type: 'number',
    unit: 'angle',
    fusionPath: 'geometry.TA',
    proShopColumn: 'taperAngle',
    metadataOnly: false,
    appliesToTypes: [
      'tapered mill', 'face mill', 'chamfer mill', 'dovetail', 'circle segment taper',
    ],
    required: false,
    precision: 4,
  },

  tip_diameter: {
    label: 'Tip Diameter (in)',
    type: 'number',
    unit: 'length',
    canonicalUnit: 'native',
    fusionPath: 'geometry.tip-diameter',
    proShopColumn: null,
    metadataOnly: false,
    appliesToTypes: [
      'chamfer mill', 'dovetail', 'thread mill', 'circle segment taper',
      'center drill', 'spot drill', 'counter sink', 'tap form', 'tap cut',
    ],
    required: false,
    precision: 4,
  },

  lower_radius: {
    label: 'Lower Radius (in)',
    type: 'number',
    unit: 'length',
    canonicalUnit: 'native',
    fusionPath: null,
    proShopColumn: null,
    metadataOnly: true,
    appliesToTypes: [
      'circle segment barrel', 'circle segment lens',
      'circle segment oval', 'circle segment taper',
    ],
    required: false,
    precision: 4,
  },

  upper_radius: {
    label: 'Upper Radius (in)',
    type: 'number',
    unit: 'length',
    canonicalUnit: 'native',
    fusionPath: null,
    proShopColumn: null,
    metadataOnly: true,
    appliesToTypes: ['face mill', 'circle segment barrel', 'circle segment taper'],
    required: false,
    precision: 4,
  },

  profile_radius: {
    label: 'Profile Radius (in)',
    type: 'number',
    unit: 'length',
    canonicalUnit: 'native',
    fusionPath: null,
    proShopColumn: null,
    metadataOnly: true,
    appliesToTypes: [
      'circle segment barrel', 'circle segment oval', 'circle segment taper',
    ],
    required: false,
    precision: 4,
  },

  axial_distance: {
    label: 'Axial Distance (in)',
    type: 'number',
    unit: 'length',
    canonicalUnit: 'native',
    fusionPath: null,
    proShopColumn: null,
    metadataOnly: true,
    appliesToTypes: ['circle segment barrel'],
    required: false,
    precision: 4,
  },

  // OOH / min_ooh: always stored in inches (see CLAUDE.md Units section)

  ooh: {
    label: 'Out of Holder (OOH)',
    type: 'number',
    unit: 'length',
    canonicalUnit: 'inches',      // ALWAYS inches — convert to native at geometry boundaries
    fusionPath: 'geometry.LB',    // per-instance field written by splitToFusionInstances
    proShopColumn: 'lengthBelowShankDiameter',
    metadataOnly: false,
    appliesToTypes: NO_TURNING,
    required: false,
    precision: 4,
  },

  min_ooh: {
    label: 'MIN OOH',
    type: 'number',
    unit: 'length',
    canonicalUnit: 'inches',      // ALWAYS inches — convert to native at geometry boundaries
    fusionPath: null,             // metadata only; reaches Fusion indirectly via shoulder_length
    proShopColumn: null,
    metadataOnly: true,
    appliesToTypes: 'all',
    required: false,
    precision: 4,
  },

  // ── Material & Coating ────────────────────────────────────────────────────

  material: {
    label: 'Tool Material',
    type: 'string',
    unit: null,
    fusionPath: 'BMC',
    proShopColumn: 'toolMaterial',
    metadataOnly: false,
    appliesToTypes: NO_TURNING,
    required: false,
    precision: null,
  },

  coating: {
    label: 'Coating',
    type: 'string',
    unit: null,
    fusionPath: null,
    proShopColumn: 'coating',
    metadataOnly: true,
    appliesToTypes: NO_TURNING,
    required: false,
    precision: null,
  },

  material_suitability: {
    label: 'Material Suitability',
    type: 'array',
    unit: null,
    fusionPath: null,
    proShopColumn: 'recommendedWorkpieceMaterial',
    metadataOnly: true,
    appliesToTypes: 'all',
    required: false,
    precision: null,
  },

  tsc_capable: {
    label: 'TSC Capable',
    type: 'boolean',
    unit: null,
    fusionPath: null,             // influences preset tool-coolant but not a dedicated Fusion field
    proShopColumn: 'throughCoolant',
    metadataOnly: true,
    appliesToTypes: 'all',
    required: false,
    precision: null,
  },

  // ── Cutting Properties ────────────────────────────────────────────────────

  helix_angle: {
    label: 'Helix Angle (°)',
    type: 'number',
    unit: 'angle',
    fusionPath: null,
    proShopColumn: 'helixAngle',
    metadataOnly: true,
    appliesToTypes: [
      'flat end mill', 'ball end mill', 'bull nose end mill', 'tapered mill', 'radius mill',
      'form mill', 'lollipop mill', 'slot/key cutter', 'thread mill', 'drill',
    ],
    required: false,
    precision: 4,
  },

  center_cutting: {
    label: 'Center Cutting',
    type: 'boolean',
    unit: null,
    fusionPath: null,
    proShopColumn: 'centerCutting',
    metadataOnly: true,
    appliesToTypes: [
      'flat end mill', 'ball end mill', 'bull nose end mill', 'tapered mill',
      'form mill', 'chamfer mill', 'lollipop mill', 'drill', 'center drill', 'spot drill',
    ],
    required: false,
    precision: null,
  },

  flute_type: {
    label: 'Flute Type',
    type: 'string',
    unit: null,
    fusionPath: null,
    proShopColumn: 'fluteType',
    metadataOnly: true,
    appliesToTypes: [
      'flat end mill', 'ball end mill', 'bull nose end mill', 'tapered mill', 'radius mill',
      'form mill', 'lollipop mill', 'slot/key cutter', 'drill',
    ],
    required: false,
    precision: null,
  },

  flute_design: {
    label: 'Flute Design',
    type: 'string',
    unit: null,
    fusionPath: null,
    proShopColumn: null,
    metadataOnly: true,
    appliesToTypes: 'all',
    required: false,
    precision: null,
  },

  cutting_direction: {
    label: 'Cutting Direction',
    type: 'string',
    unit: null,
    fusionPath: 'geometry.HAND',   // boolean true = Right Hand — Fusion-native
    proShopColumn: 'cuttingDirection',
    metadataOnly: false,
    appliesToTypes: 'all',
    required: false,
    precision: null,
  },

  backside_capable: {
    label: 'Backside Capable',
    type: 'boolean',
    unit: null,
    fusionPath: null,
    proShopColumn: 'backsideCapable',
    metadataOnly: true,
    appliesToTypes: [
      'form mill', 'dovetail', 'lollipop mill', 'slot/key cutter', 'thread mill', 'boring head',
    ],
    required: false,
    precision: null,
  },

  double_ended: {
    label: 'Double Ended',
    type: 'boolean',
    unit: null,
    fusionPath: null,
    proShopColumn: 'doubleEnded',
    metadataOnly: true,
    appliesToTypes: [
      'flat end mill', 'ball end mill', 'bull nose end mill', 'tapered mill', 'radius mill',
      'face mill', 'drill', 'center drill', 'spot drill',
    ],
    required: false,
    precision: null,
  },

  // ── Threading / Tapping ───────────────────────────────────────────────────

  pitch: {
    label: 'Thread Pitch',
    type: 'string',
    unit: null,
    fusionPath: null,
    proShopColumn: 'pitch',
    metadataOnly: true,
    appliesToTypes: ['thread mill', 'tap form', 'tap cut'],
    required: false,
    precision: null,
  },

  thread_pitch: {
    label: 'Thread Pitch (value)',
    type: 'number',
    unit: 'length',
    canonicalUnit: 'native',     // numeric pitch distance, stored in the tool's unit
    fusionPath: 'geometry.TP',   // Fusion-native; the `pitch` designation string stays metadata-only
    proShopColumn: null,
    metadataOnly: false,
    appliesToTypes: ['thread mill', 'tap form', 'tap cut'],
    required: false,
    precision: 4,
  },

  tap_class: {
    label: 'Tap Class',
    type: 'string',
    unit: null,
    fusionPath: null,
    proShopColumn: 'tapClass',
    metadataOnly: true,
    appliesToTypes: ['tap form', 'tap cut'],
    required: false,
    precision: null,
  },

  min_thread_pitch: {
    label: 'Min Thread Pitch',
    type: 'number',
    unit: null,
    fusionPath: null,
    proShopColumn: 'minThreadPitch',
    metadataOnly: true,
    appliesToTypes: ['thread mill'],
    required: false,
    precision: 4,
  },

  max_thread_pitch: {
    label: 'Max Thread Pitch',
    type: 'number',
    unit: null,
    fusionPath: null,
    proShopColumn: 'maxThreadPitch',
    metadataOnly: true,
    appliesToTypes: ['thread mill'],
    required: false,
    precision: 4,
  },

  point_type: {
    label: 'Point Type',
    type: 'string',
    unit: null,
    fusionPath: null,
    proShopColumn: 'pointType',
    metadataOnly: true,
    appliesToTypes: ['drill', 'center drill', 'spot drill', 'counter sink', 'tap form', 'tap cut'],
    required: false,
    precision: null,
  },

  stub_jobber: {
    label: 'Stub/Jobber',
    type: 'string',
    unit: null,
    fusionPath: null,
    proShopColumn: 'stubJobber',
    metadataOnly: true,
    appliesToTypes: ['drill'],
    required: false,
    precision: null,
  },

  full_profile: {
    label: 'Full Profile',
    type: 'boolean',
    unit: null,
    fusionPath: null,
    proShopColumn: 'fullProfile',
    metadataOnly: true,
    appliesToTypes: ['thread mill'],
    required: false,
    precision: null,
  },

  // ── Speeds & Feeds (mirrored from presets[0]) ─────────────────────────────

  spindle_speed: {
    label: 'Spindle Speed (RPM)',
    type: 'number',
    unit: 'rpm',
    fusionPath: 'start-values.presets[0].n',
    proShopColumn: null,
    metadataOnly: false,
    appliesToTypes: 'all',
    required: false,
    precision: 0,
  },

  cutting_feedrate: {
    label: 'Cutting Feedrate (in/min)',
    type: 'number',
    unit: 'feed',
    fusionPath: 'start-values.presets[0].v_f',
    proShopColumn: null,
    metadataOnly: false,
    appliesToTypes: 'all',
    required: false,
    precision: 4,
  },

  plunge_feedrate: {
    label: 'Plunge Feedrate (in/min)',
    type: 'number',
    unit: 'feed',
    fusionPath: 'start-values.presets[0].v_f_plunge',
    proShopColumn: null,
    metadataOnly: false,
    appliesToTypes: 'all',
    required: false,
    precision: 4,
  },

  ramp_feedrate: {
    label: 'Ramp Feedrate (in/min)',
    type: 'number',
    unit: 'feed',
    fusionPath: 'start-values.presets[0].v_f_ramp',
    proShopColumn: null,
    metadataOnly: false,
    appliesToTypes: 'all',
    required: false,
    precision: 4,
  },

  lead_in_feedrate: {
    label: 'Lead-In Feedrate (in/min)',
    type: 'number',
    unit: 'feed',
    fusionPath: 'start-values.presets[0].v_f_leadIn',
    proShopColumn: null,
    metadataOnly: false,
    appliesToTypes: 'all',
    required: false,
    precision: 4,
  },

  lead_out_feedrate: {
    label: 'Lead-Out Feedrate (in/min)',
    type: 'number',
    unit: 'feed',
    fusionPath: 'start-values.presets[0].v_f_leadOut',
    proShopColumn: null,
    metadataOnly: false,
    appliesToTypes: 'all',
    required: false,
    precision: 4,
  },

  feed_per_tooth: {
    label: 'Feed per Tooth (in)',
    type: 'number',
    unit: 'feed',
    fusionPath: 'start-values.presets[0].f_z',
    proShopColumn: null,
    metadataOnly: false,
    appliesToTypes: 'all',
    required: false,
    precision: 4,
  },

  feed_per_rev: {
    label: 'Feed per Rev (in)',
    type: 'number',
    unit: 'feed',
    fusionPath: 'start-values.presets[0].f_n',
    proShopColumn: null,
    metadataOnly: false,
    appliesToTypes: 'all',
    required: false,
    precision: 4,
  },

  cutting_speed: {
    label: 'Surface Speed (SFM)',
    type: 'number',
    unit: 'speed',
    fusionPath: 'start-values.presets[0].v_c',
    proShopColumn: null,
    metadataOnly: false,
    appliesToTypes: 'all',
    required: false,
    precision: 4,
  },

  depth_of_cut: {
    label: 'Depth of Cut (in)',
    type: 'number',
    unit: 'length',
    canonicalUnit: 'native',
    fusionPath: null,
    proShopColumn: null,
    metadataOnly: true,
    appliesToTypes: 'all',
    required: false,
    precision: 4,
  },

  width_of_cut: {
    label: 'Width of Cut (in)',
    type: 'number',
    unit: 'length',
    canonicalUnit: 'native',
    fusionPath: null,
    proShopColumn: null,
    metadataOnly: true,
    appliesToTypes: 'all',
    required: false,
    precision: 4,
  },

  // ── Metadata / Admin ──────────────────────────────────────────────────────

  notes: {
    label: 'Notes',
    type: 'string',
    unit: null,
    fusionPath: null,
    proShopColumn: null,
    metadataOnly: true,
    appliesToTypes: 'all',
    required: false,
    precision: null,
  },

  tags: {
    label: 'Tags',
    type: 'array',
    unit: null,
    fusionPath: null,
    proShopColumn: null,
    metadataOnly: true,
    appliesToTypes: 'all',
    required: false,
    precision: null,
  },

  last_used_job: {
    label: 'Last Used Job',
    type: 'string',
    unit: null,
    fusionPath: null,
    proShopColumn: null,
    metadataOnly: true,
    appliesToTypes: 'all',
    required: false,
    precision: null,
  },

  preferred_machine: {
    label: 'Preferred Machine',
    type: 'string',
    unit: null,
    fusionPath: null,
    proShopColumn: null,
    metadataOnly: true,
    appliesToTypes: 'all',
    required: false,
    precision: null,
  },

  updated_by: {
    label: 'Updated By',
    type: 'string',
    unit: null,
    fusionPath: null,
    proShopColumn: null,
    metadataOnly: true,
    appliesToTypes: 'all',
    required: false,
    precision: null,
  },

  revision_notes: {
    label: 'Revision Notes',
    type: 'string',
    unit: null,
    fusionPath: null,
    proShopColumn: null,
    metadataOnly: true,
    appliesToTypes: 'all',
    required: false,
    precision: null,
  },

  // ── System / Collection fields ────────────────────────────────────────────

  presets: {
    label: 'Presets',
    type: 'array',
    unit: null,
    fusionPath: 'start-values.presets',
    proShopColumn: null,
    metadataOnly: false,
    appliesToTypes: 'all',
    required: false,
    precision: null,
  },

  assemblies: {
    label: 'Assemblies',
    type: 'array',
    unit: null,
    fusionPath: null,
    proShopColumn: null,
    metadataOnly: true,
    appliesToTypes: 'all',
    required: false,
    precision: null,
  },

  selected_holder_guid: {
    label: 'Selected Holder',
    type: 'string',
    unit: null,
    fusionPath: null,
    proShopColumn: null,
    metadataOnly: true,
    appliesToTypes: 'all',
    required: false,
    precision: null,
  },

  merge_history: {
    label: 'Merge History',
    type: 'array',
    unit: null,
    fusionPath: null,
    proShopColumn: null,
    metadataOnly: true,
    appliesToTypes: 'all',
    required: false,
    precision: null,
  },

  created_at: {
    label: 'Created',
    type: 'string',
    unit: null,
    fusionPath: null,
    proShopColumn: null,
    metadataOnly: true,
    appliesToTypes: 'all',
    required: false,
    precision: null,
  },

  updated_at: {
    label: 'Last Updated',
    type: 'string',
    unit: null,
    fusionPath: null,
    proShopColumn: null,
    metadataOnly: true,
    appliesToTypes: 'all',
    required: false,
    precision: null,
  },
};

// ── Helper functions ───────────────────────────────────────────────────────

/**
 * Returns field names that apply to the given tool type.
 * Use this in ToolForm to determine which fields to show.
 */
export function fieldsForType(toolType) {
  return Object.entries(FIELD_REGISTRY)
    .filter(([, def]) => {
      if (def.appliesToTypes === 'all') return true;
      return def.appliesToTypes.includes(toolType);
    })
    .map(([fieldName]) => fieldName);
}

/**
 * Returns registry entries for all fields that are Fusion-native
 * (fusionPath !== null and metadataOnly === false).
 */
export function fusionNativeFields() {
  return Object.entries(FIELD_REGISTRY)
    .filter(([, def]) => def.fusionPath !== null && !def.metadataOnly)
    .map(([fieldName, def]) => ({ fieldName, ...def }));
}

/**
 * Returns registry entries for all fields that appear in ProShop CSV export.
 * Result is ordered by insertion order in FIELD_REGISTRY, which is designed
 * to match the ProShop column conventions.
 */
export function proShopFields() {
  return Object.entries(FIELD_REGISTRY)
    .filter(([, def]) => def.proShopColumn !== null)
    .map(([fieldName, def]) => ({ fieldName, ...def }));
}

/**
 * Returns true if the field applies to the given tool type.
 */
export function fieldAppliesTo(fieldName, toolType) {
  const def = FIELD_REGISTRY[fieldName];
  if (!def) return false;
  if (def.appliesToTypes === 'all') return true;
  return def.appliesToTypes.includes(toolType);
}

/**
 * Returns true if the field is metadata-only (never written to Fusion JSON).
 */
export function isMetadataOnly(fieldName) {
  return FIELD_REGISTRY[fieldName]?.metadataOnly === true;
}
